import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/obsidian/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"node-pty",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "node",
	loader: {
		".md": "text",
	},
});

if (prod) {
	await context.rebuild();

	// migrate-links CLI를 standalone 번들로 빌드
	await esbuild.build({
		entryPoints: ["scripts/migrate-links.ts"],
		bundle: true,
		format: "esm",
		target: "es2020",
		platform: "node",
		outfile: "migrate-links.mjs",
		banner: { js: "" },
	});

	process.exit(0);
} else {
	await context.watch();
}
